spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 9
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentms?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: root
  freemarker:
    template-loader-path: classpath:/templates/
  mail:
    email: 15224973394@163.com
    host: smtp.163.com
    port: 465
    username: 15224973394
    # 授权密码， 非邮箱密码，授权码是用于登录第三方邮件客户端的专用密码。
    password: TEBVOQSTHVTBEFVC
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps

code:
  expiration: 300



logging:
  level:
    com.zhiend.student_server: info
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  type-aliases-package: com.zhiend.student_server.entity
#  mapper-locations: classpath:mapper/*.xml
  mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml文件地址，当前这个是默认值。
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto # 全局id类型为自增长
      update-strategy: not_null
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 10086


knife4j:
  enable: true
  openapi:
    title: 学生管理接口文档
    description: "学生管理接口文档"
    email: sse_d@qq.com
    concat: zhiend
    url: http://localhost:10086/doc.html
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.zhiend.student_server.controller


